- neomodel/contrib/semi_structured.py
- neomodel/core.py
- neomodel/relationship.py
- neomodel/relationship_manager.py
- neomodel/util.py
- setup.py
- test/__init__.py
- test/test_cypher.py
This PR provides the updates necessary to move towards py2neo 2.x. Functionality remains largely backwards compatible except for the known move from raising a `CypherException` to raising an `InvalidSyntax` when a cypher query has invalid syntax. This provides a more clear indication as to what is going wrong.
* Pypy tests are not passing on TravisCI
* Need to transition `START`queries to `MATCH`
* Documentation surrounding Neo4j 2.2.x requirements
* Information primarily directing users to py2neo's docs on setting a new password for a new db
I believe 2 and 3 in the list above are outside the scope of this PR and should be moved into separate issues. As for pypy support I'm not sure what is causing the issue and am not up on pypy so I was hoping during the review someone could assist in …
> Initial modifications to support py2neo 2.x

- neomodel/exception.py
- test/test_exceptions.py
This commit will fix the previous type error when there was a None type
as java exception.
We have noticed this while running our continuous integration.  When printing the follow exception:
CypherException: 
None: None
Query: CREATE CONSTRAINT on (n:UserNode) ASSERT n.username IS UNIQUE; 
Params: None
Trace: None
There was a typeError on 
```python
File "/home/andrefsp/.virtualenvs/depop/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
self.test(*self.arg)
File "/home/andrefsp/development/depop/neomodel/test/test_exceptions.py", line 12, in test_cypher_exception
print CypherException("SOME QUERY", (), "ERROR", None, None)
File "/home/andrefsp/development/depop/neomodel/neomodel/exception.py", line 42, in __str__
trace = "\n    ".join(self.java_trace)
TypeError: 
``` …
> CypherException logging TypeError exception

- neomodel/util.py
otherwise the split is done in the wrong place, cutting the password itself
> rsplit on @ char, this allows passing passwords with "@" chars

- neomodel/match.py
passing order_by results in an invalid cypher count query
> on _count() call make sure "order_by" is not built into the query

- neomodel/relationship_manager.py
make sure RelationshipManager.get() call raises:
- MultipleNodesReturned
- DoesNotExist 
accordingly same as NodeSet.get()
additionally use repr() call same as NodeSet.get(), avoids str() calls that fail with unicode values
> conform errors NodeSet.get() and RelationshipManager.get()

- neomodel/match.py
when the NodeSet is a "complex" one built on top of a Traversal etc. this call fails as the check is on the self.node_set, when the source is an inner NodeSet.
> check "order_by" on source and not self

- doc/source/batch.rst
- neomodel/core.py
- neomodel/util.py
- test/test_batch.py
- test/test_indexing.py
- test/test_transactions.py
contains implementations for:
- ```StructuredNode.create()``` - re-written with batch transaction.
- ```StructuredNode.create_or_update()``` - update or create a node by its' required fields, updating any optional fields.
- ```StructuredNode.get_or_create()``` - lookup or create a node by its' required fields.
All three methods use batch transactions, and optionally support streaming.
This continues the discussion on issue https://github.com/robinedwards/neomodel/issues/108, and work done by @iwalu in PRs https://github.com/robinedwards/neomodel/pull/167 and https://github.com/robinedwards/neomodel/pull/175  
_*_ docs and test will be updated if the implementation is accepted
**see https://github.com/robinedwards/neomodel/issues/108#issuecomment-128119565 for more information**
> feature insert or update

- neomodel/contrib/semi_structured.py
- neomodel/core.py
- neomodel/properties.py
- neomodel/util.py
**parameterized bulk queries**
utilize passing property maps for MERGE and CREATE queries
see: http://neo4j.com/docs/stable/cypher-parameters.html#_create_multiple_nodes_with_properties
and: http://neo4j.com/docs/stable/query-set.html#set-adding-properties-from-maps
this provides significant speed up for hundreds of nodes
**add "lazy" ID only query results**
significant (seconds) speed up for hundreds of nodes where property values are not required for further operations
**cache all most used `defined_properties()`**
this method is called multiple times for each node class `init()`, this provides additional optimization when inflating nodes.
> performance enhancements for bulk operations 

- doc/source/properties.rst
- neomodel/core.py
- neomodel/match.py
- neomodel/properties.py
- test/test_properties.py
You are now able to use different names for the property in the database and the python node attribute.
This is quite useful, for "hiding" the property behind a "python property" subsequently. So you don't need to rename you database fields.
For example renaming the property "name" to "name_" and adding a "python @property" "name" afterwards.
Usages:
name_ = StringProperty(db_property="name")
name = StringProperty(db_property="full_name")
> Add "db_property" as parameter to Property.

- neomodel/properties.py
`default = 0` evaluates to false, which it is not when we're talking about numbers.
> In case of numeric properties default && required check doesn't work as expected

- neomodel/match.py
Don't append empty filters to filters list. Otherwise this leads to self.filters not being evaluated as false leading to empty where statements in cypher query
> Bugfix empty filter append

- neomodel/match.py
* Makes the library python 3 compatible, without this change, the error 
```Error “ 'dict' object has no attribute 'iteritems' ”``` when trying to add properties
to a relation.
> python3: use .items() instead of deprecated .iteritems()

- neomodel/config.py
- neomodel/util.py
This change makes the encrypted parameter for  the driver connection configurable (by default is set to True, that means that all connections are encrypted):
`GraphDatabase.driver('bolt://' + hostname, auth=basic_auth(username, password), encrypted=self.encrypted)`
This is useful in case that you want to have multiple neo4j instances and access them without having problems because of the checking of '~/.neo4j/known_hosts' certificate.
This is a common situation in a development environment as described in the Neo4j documentation in section [4.3.2.1. Encryption and authentication](https://neo4j.com/docs/developer-manual/current/drivers/configure-connect/).
> Encrypted connections parameter configurable

- neomodel/match.py
Since `RelationshipTo` and `RelationshipFrom` both set model to None in their constructors, the test needs to be for `model is None` not just for the `'model'` key being missing.
> Test for model is None in Traversal.match()

- doc/source/getting_started.rst
- neomodel/core.py
- scripts/neomodel_remove_labels
- setup.py
- test/test_label_drop.py
This feature is supposed to add functionality similar to neomodel_install_labels, just instead of creating new indexes and constraints it removes all existing ones.
Code is modeled after install_labels example.
Test is also added that remove all indexes and constraints and then reinstall all removed again not to mess up with other tests.
This feature was missing because manually removing installed labels especially when there is a lot of them is tedious work.
> Add feature for removing constraints and indexes from schema

- neomodel/util.py
I setup the database url using this `config.DATABASE_URL = 'DATABASE URL'`. In the case where docker container for neo4j spins up but is not ready to accepts the connection and the application tries to connect to the db. The `ServiceUnavailable` exception will be raised. In that case, the `self.driver` value is still `None`, however, `self.url` is already set to the new url. When `ensure_connection` is called, it checks if the `self.url` exist and in this case, it does ! Therefore, it tries to proceed and it ran into the problem accessing `session()` function from a `None` object. The `db` will permanently in the state where it cannot operate.
only set `self.url` upon successful server connection
> Fix None driver issue with service unavailable issue

- neomodel/core.py
- test/test_properties.py
When calling `get_or_create` on a node that already exists and has a property with `db_property` set, I would get the error `Cannot merge node using null property value for var_name`, which is now addressed in `core.py` by checking to see if `db_property` is set on the property.
> Respect db_property on model properties in get_or_create

- doc/source/relationships.rst
Using the documentation as is provides the error `TypeError: RelationshipFrom() takes at least 2 arguments (2 given)`.
> Add missing parameter in Relationships documentation

- neomodel/core.py
- test/test_label_install.py
Currently, `neomodel_install_labels` uses the wrong property name when a `UniqueIdProperty` has `db_property` set. This PR fixes that.
Reproducer:
```python
class ContainerBuilds(StructuredNode):
id_ = UniqueIdProperty(db_property='id')
```
Then run `neomodel_install_labels` on the file. It will create the unique constraint on `id_` instead of `id`.
> Respect when db_property is set in install_labels

- doc/source/getting_started.rst
- neomodel/match.py
- test/test_models.py
I'm used to SQLAlchemy and they have a handy [first](http://docs.sqlalchemy.org/en/latest/orm/query.html#sqlalchemy.orm.query.Query.first) method. This PR implements something very similar to that but instead matches the behavior of `get` and `get_or_none` for consistency.
> Add the "first" and "first_or_none" methods on the NodeSet class

- doc/source/getting_started.rst
- neomodel/cardinality.py
- neomodel/relationship_manager.py
- test/test_cardinality.py
- test/test_relationships.py
My project that uses neomodel requires replacing all existing relationships with a new one. I found myself doing this by looping through all the connected nodes and disconnect the relationships individually. This was repetitive across the code base and inefficient. This PR adds the ability to replace all relationships of a specific type with a new one. It also adds the ability to remove all existing relationships of a specific type.
> Add the "disconnect_all" and "replace" methods on relationship properties

- setup.py
neomodel is packaged in EPEL (Extra Packages for Enterprise Linux) for EL7 (RHEL 7/CentOS 7) and the latest version of pytz available on EL7 is 2016.10. Having the version of pytz too high makes it so that neomodel can't be packaged for EL7 and current versions of Fedora (Fedora uses version 2017.2).
> Lower the required pytz version

- doc/source/transactions.rst
- neomodel/util.py
Causal clustering has a leader and multiple followers. Only leader can be written to.
Initiating a transaction with `@db.transaction` doesn't seem to allow the specifying of a transactionality type (Bolt is READ or WRITE), thus it's possible that the `bolt+routing` protocol could route a write transaction to a follower.
This PR allows the developer to choose `@db.write_transaction`, which will set `access_mode` to `"WRITE"`, directing Bolt to the leader of a causal cluster. It defaults to the previous behaviour to avoids backwards compatibility issues.
> Explicit write transaction mode

- neomodel/contrib/semi_structured.py
- neomodel/core.py
- neomodel/relationship_manager.py
- neomodel/util.py
- setup.py
- test/test_properties.py
In the v1.6 of the Python Neo4j driver, `properties` got renamed to `_properties`. This PR adds a compatibility for both ways.
> Support neo4j-driver v1.6.0

- neomodel/match.py
- test/test_match_api.py
Some of my structured nodes have properties that end with an underscore to not override default methods like `hash`. I ran into an issue when I tried to filter on those properties. This PR corrects that.
> Support filtering on properties that end with an underscore

- neomodel/match.py
- test/test_match_api.py
If you're trying do this
```
SomeModel.nodes.filter().filter(arg1=val1).all()
```
neomodel throws exception like this
```
MATCH (somemodel:SomeModel) WHERE AND somemodel.arg1={arg1_1} RETURN ....
```
I fixed it. Sorry for my bad english
> Empty filter bug

- doc/source/batch.rst
- doc/source/configuration.rst
- doc/source/extending.rst
- doc/source/getting_started.rst
- doc/source/hooks.rst
- doc/source/module_documentation.rst
- doc/source/properties.rst
- doc/source/queries.rst
- doc/source/relationships.rst
- doc/source/transactions.rst
- neomodel/__init__.py
- neomodel/core.py
- neomodel/exceptions.py
- neomodel/match.py
- neomodel/relationship.py
- neomodel/relationship_manager.py
- neomodel/util.py
- test/conftest.py
- test/test_issue283.py
- test/test_relationship_models.py
Initial work on rectifying issue 283, outlined [here](https://github.com/neo4j-contrib/neomodel/issues/283) and in more detail [here](https://github.com/aanastasiou/neomodelInheritanceTest).
A "class registry" has been added in `util.Database`. It is populated automatically by `core.NodeMeta.__new__` and subsequently used by `util.Database.cypher_objectaware_query` to properly instantiate query results to objects in a hierarchy.
This is **effected** by `match.QueryBuilder._execute` (which now uses `cypher_objectaware_query`) when the entity is instantiated **from** the database and **enforced** by `relationship_manager.RelationshipManager._check_node` when a connection between two entities is attempted to be established. The latter now tests for `issubclass` rather than `isinstance`.
To …
> Initial work on issue 283 - "Inheritance Breaks"

- neomodel/match.py
- test/test_match_api.py
Filtering left hand traversal statement is not possible. Top level NodeSet source class is used to process filter args for all sources in the chain. 
For each NodeSet in the chain current source_class should be passed, not the top level.
This one was not possible
` NodeSet(Coffee.nodes.filter(price=11).suppliers).filter(delivery_cost=3).all() `
```
neomodel/match.py:469: in all
return self.query_cls(self).build_ast()._execute()
neomodel/match.py:219: in build_ast
self.build_source(self.node_set)
neomodel/match.py:235: in build_source
ident = self.build_source(source.source)
neomodel/match.py:230: in build_source
return self.build_traversal(source)
neomodel/match.py:271: in build_traversal
lhs_ident = self.build_source(traversal.source)
neomodel/match.py:243: in build_source …
```
> add possibility to filter traversal left hand statements

- neomodel/util.py
Issue #378 describes the problem in neomodel v3.3.0 in which the new node-class-registry container fails to map node class names to node class instances. 
The problem was narrowed to the place that container is initialized which is during initialization of Database instance.
The refactor in this pull request is the creation of a singleton class (NodeClassRegistry) whose subclasses share the same container for the aforementioned mapper. Therefore, on every Database initialization, the container is intact and not initialized for multiple times.
The Database class inherits from this new class.
> Refactor of Node Class Registry container used by util.Database.

- neomodel/core.py
Hi,
I was using create_or_update to create node with a specified `relationship`, and I noticed `_rel_helper` function in `_build_merge_query` is always invoked with `OUTGOING` direction ignoring the `relationship` actual direction.
I thought it would be useful to use `relationship.definition['direction']`' instead (also, I had to adjust `lhs` and `rhs`), to dynamically determine the relationship direction.
Thanks.
> Add _build_merge_query dynamic relationship direction

- README.rst
- doc/source/batch.rst
- doc/source/extending.rst
- doc/source/getting_started.rst
- doc/source/queries.rst
- doc/source/relationships.rst
- doc/source/spatial_properties.rst
- neomodel/core.py
- neomodel/exceptions.py
- neomodel/util.py
- test/test_contrib/test_spatial_datatypes.py
- test/test_contrib/test_spatial_properties.py
- test/test_exceptions.py
- test/test_issue283.py
- test/test_properties.py
- test/test_relationships.py
- test/test_transactions.py
Please see `doc/extending.rst` section "Caveats" for a detailed explanation of the safeguard added with this commit.
An exception (`ClassAlreadyDefined`) is raised, if a class is attempted to be defined that happens to have exactly the same set of labels with another class that may have already been defined within the node-to-class registry.
> Added safeguard for the accidental redefinition of a class mapping

- doc/source/properties.rst
- neomodel/__init__.py
- neomodel/properties.py
- test/test_properties.py
Add a DateTimeFormatProperty so user can create a time property like that.
``` python
some_format = "%Y-%m-%d %H:%M:%S"
timestamp = DateTimeFormatProperty(format=some_format)
```
Also add a test in test_properties.py to test the function.
> Add a DateTimeFormatProperty which allows integrating with custom date format

- setup.py
Fixes `setup.py` implementation to properly exclude `test` package and `test.test_contrib` subpackage
Checked it is working as follows:
```
>>> from setuptools import setup, find_packages
>>> find_packages(exclude=('tests',))
['test', 'neomodel', 'test.test_contrib', 'neomodel.contrib']
>>> find_packages(exclude=('test',))
['neomodel', 'test.test_contrib', 'neomodel.contrib']
>>> find_packages(exclude=('test', 'test.*'))
['neomodel', 'neomodel.contrib']
```
> fix in setup.py find_packages to exclude test package

- .travis.yml
Travis CI builds have been failing for a while because Oracle Java 8 is no longer available.
This change switches the Travis builds to use OpenJDK instead.
> Fix the travis-ci build by replacing Oracle Java with Openjdk.

- doc/source/getting_started.rst
Responding to:
`DeprecationWarning: search() is now deprecated please use filter() and exclude()`
> Add example of `exclude()`

- neomodel/core.py
Pretty sure that `cls` is universally used, `kls` doesn't seem to be used anywhere else in this library.
> Correct inconsistent naming kls to cls

- neomodel/properties.py
- test/test_properties.py
This change makes properties that have `unique_index=True` nullable, which is allowable as per the neo4j documentation.
Previously, properties marked as a unique index were required.
See https://github.com/neo4j-contrib/neomodel/issues/267
> Make properties with unique index nullable

- setup.py
pytest is not a runtime dependency and thus should not
be listed in `install_requires`. This lowers the amount
of dependencies that are pulled in when installing neomodel.
> Stop making pytest an installation requirement

- doc/source/configuration.rst
- doc/source/getting_started.rst
- neomodel/util.py
Resolve https://github.com/neo4j-contrib/neomodel/issues/526
Driver database documentation: https://neo4j.com/docs/api/python-driver/4.1/api.html#database
With this PR, we can specify the database name in the neo4j or bolr URL:
`bolt://neo4j:neo4j@localhost:7687` => default database
`bolt://neo4j:neo4j@localhost:7687/mydb` => `mydb` database
> Add support for multi databases

- neomodel/util.py
This PR enhances the logging within the cypher_query method in ```neomodel.utils.py``` so that logging can be enabled only for queries that take longer than a specified amount of time. This is useful as the Neo4j query log is not available on the community edition and sometimes you only wish to log the slow queries and not everything especially if you are working on a production environment.
The logging uses a new optional environmental variable **NEOMODEL_SLOW_QUERIES** which can be set to a string whose value is thew threshold at which you want to start recording queries.
E.G If you set the value to the following ```os.environ["NEOMODEL_SLOW_QUERIES"] = "0.09"``` then only queries taking more than 0.09 seconds will be logged.
If the variable is not set, then it defaults to 0 and acts as …
> Add support for slow query log

- .gitignore
- neomodel/properties.py
- test/test_models.py
DateProperty requires datetime data type and in deflate() it's converted to isoformat of view YYYY-MM-DDTHH:MM:SS. Then inflate() tries to convert it back to datetime by using strptime(.., "%Y-%m-%d"), which doesn't deal with 'THH:MM:SS'. 
Fixed with removing time part of the string. Tested on Python 3.6
> Fix DateProperty inflate

- neomodel/__init__.py
Ref: https://docs.python.org/3.9/library/importlib.metadata.html#module-importlib.metadata
Ref: https://github.com/googleapis/python-api-core/issues/27#issuecomment-676563754
(@pganssle is CPython Core Dev. :))
pkg_resources is causing a few issues for us, particularly in lambda envs
This is a much better way in Python 3.8+
cc @whatSocks @nossila
> Use modern python API for metadata

- neomodel/core.py
Adding a second exception being ignored to ensure compatibility after neo4j 4.4 update, as well as future updates which might reproduce the same change.
Reason and explanation for this PR are in issue #595
> Ensure compatibility after neo4j 4.4 update

- neomodel/match.py
- neomodel/relationship_manager.py
- test/test_relationships.py
As of 3.3.2, it is not possible to do `Person.friends.filter(Q(age__lt=25) | Q(name__exact="John"))` (it raises a `TypeError`).
This PR should make it possible.
> Add support for Q objects on relationship_manager.filter and .exclude

- neomodel/exceptions.py
It should be `db_node_rel_class` instead of `db_node_class`. 
This caused the exception to raise an exception by itself.
> Fixed wrong attribute in `NodeClassAlreadyDefined`

- neomodel/relationship_manager.py
If [django_neomodel](/neo4j-contrib/django-neomodel) is used and the model definition is dynamically generated with the `type()` builtin like described in #318, the stack frame number used in the `RelationshipDefinition` might be wrong (off by one - but might be even more off in other situations) and the class definition will not be found. This results in an exception like `module 'importlib._bootstrap' has no attribute 'NodeClass'` where `NodeClass` is the node class used in the relationship.
Currently, the `RelationshipDefinition` uses a hard coded frame number to retrieve the node class used for a relationship. Depending on the stack layout, this might be the wrong frame. Therefore this PR suggests to use Python's inspect module to search all outer frames for the node class and use the …
> Search frames for class in RelationDefinition

- neomodel/util.py
It's an error close to error #551, but in the case of rollback failure. I got such corruption in my project during high load on the database.
Also, autoformatted refactor imports a bit and removed unnecessary spaces.
> Fix transaction corruption

- doc/source/cypher.rst
I noticed that the documentation wasn't updated for the new parameter syntax (you are now required to use `$field` instead of `{field}`). I also added some more info on automatic class resolution.
> Improve and Update Documentation on Cypher Queries

- neomodel/relationship_manager.py
Provides performance improvements for changes introduced in #603
Instead of loading the whole stack frame at once, these changes allow incrementally loading frames as needed.
In general, only the 3-6 outermost frames are needed.
We tested the changes from #603 in a large project and saw the time that takes to instantiate `RelationshipDefinition` go up for up to 10 seconds from a baseline of milliseconds. This observations were made at import time, where the stack trace is huge.
> improve RelationshipDefinition constructor performance

- doc/source/properties.rst
This PR fixes a link on the property types page. Currently the text leads to `http://www.google.com` while it probably should lead to the Notes section where the notes are.
> Fix link in documentation

- README.rst
- doc/source/conf.py
- doc/source/index.rst
- neomodel/__init__.py
As per the title of the PR, please note manual module metadata (`__version`) setting for the moment at least.
> Minor corrections to get the documentation rebuilt with zero errors.

- pyproject.toml
This PR solves two problems with `pyproject.toml` on `4.0.10`:
1. The version is brought back to "static" (to resolve problems with installing a local (dev) version); and more importantly
2. The `neomodel` scripts getting their proper names
* In `4.0.10` they are installed as `install-labels`
> Modified pyproject.toml to properly install the neomodel scripts

- .gitignore
- Changelog
- neomodel/core.py
- neomodel/relationship.py
- neomodel/relationship_manager.py
Deprecated methods since version 3 with deprecation notice :
- StructuredRel.delete() - _Replaced by .disconnect()_
- RelationshipManager.search() - _Replaced by .filter() and .exclude()_
> Remove deprecated methods

- neomodel/util.py
- test/test_issue283.py
Implements #715 
I am not really convinced about the implementation but I couldn't manage to do better without rewriting half of the package.
I welcome discussion and comments on this pull request.
I have not implemented tests but they will come as soon as I have time.
I've run all the tests except those for "Aura" because I don't know what it is. They finished succesfully.
> Added automatic path inflation

- Changelog
- doc/source/relationships.rst
- neomodel/core.py
- neomodel/util.py
- test/conftest.py
- test/test_contrib/test_spatial_datatypes.py
- test/test_dbms_awareness.py
- test/test_driver_options.py
- test/test_indexing.py
- test/test_label_install.py
- test/test_models.py
Feature introduced in Neo4j 5.7. Throws a FeatureNotSupported exception if used while connected to a <5.7 Neo4j database.
Also add some tests for database version and edition detection.
> Add support for relationship uniqueness constraints

- Changelog
- neomodel/match.py
- test/test_match_api.py
See #589 
To prevent this, when building a traversal, name the target node as "{traversal_name}_{relationship_name}".
So the new query will look like :
`MATCH (extension) WHERE id(extension)=12796 WITH extension MATCH ((extension)-[r1:extension]->(extension_r1:Extension)) RETURN extension_r1`
> Fix #589 match relationship with same name as source and target nodes

- doc/source/getting_started.rst
- docker-scripts/docker-neo4j.sh
- neomodel/scripts/neomodel_inspect_database.py
- pyproject.toml
- test/data/neomodel_inspect_database_output.txt
- test/test_scripts.py
> Database introspection script

- neomodel/cardinality.py
- neomodel/core.py
- neomodel/match.py
- test/test_models.py
If a node object is initialised but not yet saved to the database, then its `element_id` should return a suitable value to denote that the object is unsaved. Before switching to `element_id`, we used to examine the `_id` of an element to be able to tell if the node was saved or not. 
The intention [seems to be there](https://github.com/neo4j-contrib/neomodel/blob/master/test/test_models.py#L104) but since `element_id_property` is a dynamical property, [it was not getting a default value](https://github.com/neo4j-contrib/neomodel/blob/master/neomodel/core.py#L412). (Unsaved nodes do not have their `element_id` property at all and therefore `.element_id` was failing. On the same subject, [this line](https://github.com/neo4j-contrib/neomodel/blob/master/neomodel/core.py#L761) had to be …
> Bug fix in `element_id`.

- README.md
- neomodel/__init__.py
The `pkg_resources` import is unused and it requires users to have `setuptools` installed.
> chore: remove runtime dependency on `pkg_resources`

- neomodel/match.py
- test/test_match_api.py
Issue was when count was used in combination with skip/limit.
Had to change the query builder so that pagination happens to variables before the count aggregation is applied.
> Incorrect query for count of objects #769

- neomodel/util.py
Hi all,
first for all, thanks for your work and for keeping up to date this library!
I'm using `neomodel` in a FastAPI project to update a neo4j database. For each endpoint reading or writing to the database, I open a new DB transaction using the decorators `write_transaction` and `read_transaction`. 
Since I'm using multiple wrappers from different libraries for each endpoint, I noticed that the `TransactionProxy` `__init__` and `__call__` functions were called when creating the endpoint, but the `wrapper` defined in `__call__` and the `__enter__` and `__exit__` functions were not invoked.
This pull request adds the `functools` `wraps` function to that `wrapper`. Doing this I resolved the problem described before. 
I executed the tests with pytest and they passed. I also noticed that the …
> Add wraps to wrapper defined in TransactionProxy

- neomodel/core.py
github: [https://github.com/neo4j-contrib/neomodel/issues/778](Structured Node __eq__ works incorrectly for non-persisted nodes.)
> fix(core): compare objects by id in memory if they are different

- neomodel/match.py
- test/test_match_api.py
I improved the IN filter so that it supports correct usage with the ArrayProperty. I didn't want to make any radical changes. If you agree, I could implement what was suggested in some issues like https://github.com/neo4j-contrib/neomodel/issues/284 and https://github.com/neo4j-contrib/neomodel/issues/379 - the possibility of filtering by contains_values and/or exact_values.
> feat(match): allow filtering by IN the ArrayProperty

- doc/source/getting_started.rst
I had issues trying to understand where to put my authentication for `neomodel_inspect_data` since it isn't in the --help flag either so I've outlined it clearer within the docs
> Updated docs so connection is clearer

- neomodel/scripts/neomodel_inspect_database.py
- test/data/neomodel_inspect_database_output.txt
- test/data/neomodel_inspect_database_output_light.txt
- test/data/neomodel_inspect_database_output_pre_5_7.txt
- test/data/neomodel_inspect_database_output_pre_5_7_light.txt
- test/test_scripts.py
Fixes a bug where neomodel_inspect_database would incorrectly parse Date property
> Fix DateProperty bug in inspection script

- neomodel/async_/match.py
- neomodel/sync_/match.py
- test/async_/test_match_api.py
- test/sync_/test_match_api.py
> Fix async node iterator

- doc/source/extending.rst
- neomodel/async_/core.py
- neomodel/async_/relationship_manager.py
- neomodel/exceptions.py
- neomodel/sync_/core.py
- neomodel/sync_/relationship_manager.py
- test/async_/test_registry.py
- test/sync_/test_registry.py
Today, neomodel uses a single node class registry, to prevent collision of labels inside the database.
So this would not work :
```
class PatientOne(AsyncStructuredNode):
__label__ = "Patient"
name = StringProperty()
class PatientTwo(AsyncStructuredNode):
__label__ = "Patient"
identifier = StringProperty()
```
This PR adds a database-specific node class registry so that in the context of multiple databases, two different StructuredNode classes can map into the same label, but in different databases :
```
class PatientOne(AsyncStructuredNode):
__label__ = "Patient"
__target_databases__ = ["db_one"]
name = StringProperty()
class PatientTwo(AsyncStructuredNode):
__label__ = "Patient"
__target_databases__ = ["db_two"]
identifier = StringProperty()
```
> Add db specific node class registry

- docker-scripts/docker-neo4j.sh
- neomodel/async_/match.py
- neomodel/sync_/match.py
- test/async_/test_match_api.py
- test/sync_/test_match_api.py
This is a simple attempt to rebuild a subgraph hierarchy based from a call to fetch_relations().
Each node in the result will have a extra _relations property which contains a dictionary of this node's relation(s). Can be useful to automate further processing like transforming a node and its relations to another representation.
> Added method to resolve a subgraph from a fetch_relations() call.

- neomodel/async_/match.py
- neomodel/sync_/match.py
- test/async_/test_match_api.py
- test/sync_/test_match_api.py
Simple way to include one or more subqueries within a NodeSet context
> Subqueries support

- neomodel/async_/match.py
- neomodel/properties.py
- neomodel/sync_/match.py
- test/async_/test_match_api.py
- test/sync_/test_match_api.py
Use related node properties in filtering and ordering calls.
> Traversal support for filtering and ordering

- .github/workflows/integration-tests.yml
- neomodel/async_/match.py
- neomodel/sync_/match.py
- test/async_/test_match_api.py
- test/sync_/test_issue283.py
- test/sync_/test_match_api.py
Can be useful for complex ordering needs.
> Allow use of raw cypher statement as argument of order_by()

- Changelog
- doc/source/advanced_query_operations.rst
- neomodel/async_/match.py
- neomodel/sync_/match.py
- neomodel/typing.py
- test/async_/test_match_api.py
- test/sync_/test_match_api.py
New syntax to allow more complex statements when injecting intermediate transformation:
* Use of DISTINCT clause
* Indicate item property instead of complete item
* Indicate if transformed variable should be returned by query or not
> Improved intermediate_transform method.

- neomodel/async_/match.py
- neomodel/sync_/match.py
- test/async_/test_match_api.py
- test/sync_/test_match_api.py
Move everything to the latest WHERE statement instead.
> Do not prevent mixed filters when using OR operator.
