neo4j-contrib/neomodel

- .travis.yml
- README.rst
- neomodel/core.py
Building off of some new functionality from py2neo 2.x this PR enables us to close #136.
> Index and Unique Constraint Checks

- neomodel/util.py
sorry missed, maxsplit=1 (as more than one @ is expected)
> rsplit fix

- doc/source/relationships.rst
- neomodel/match.py
add support for additional relationship types:
* ``None`` = [unnamed directional relationships](http://neo4j.com/docs/stable/query-match.html#match-outgoing-relationships) by target node type
* ``*`` = [variable_length](http://neo4j.com/docs/stable/introduction-pattern.html#_variable_length) by target node type
> feature wildcard and non explicit traversal

- doc/source/queries.rst
- neomodel/match.py
- test/test_match_api.py
added support for additional "django" operators for field filter:
* in
* isnull
* exact/iexact
* contains/icontains
* endswith/iendswith
* startswith/istartswith
* regex/iregex
> extended django filters support

- doc/source/relationships.rst
Class Person defined property friends
later references used friend
Corrected later references to use friends
> fixed typo in Properties section

- neomodel/match.py
- test/test_match_api.py
Following #214 , here is a proposal to handle random ordering mimicing the Django order_by('?')
> allow for random ordering, mimicing the Django order_by('?')

- doc/source/extending.rst
UserMixin was wrongly written as User. 
Please review and check. 
Thanks.
> Fixed type for UserMixin

- neomodel/core.py
> Adds newline to is abstract warning #305

- doc/source/index.rst
- doc/source/module_documentation.rst
- doc/source/properties.rst
- doc/source/relationships.rst
- neomodel/cardinality.py
- neomodel/core.py
- neomodel/match.py
- neomodel/properties.py
- neomodel/relationship_manager.py
This commit mainly intends to improve the documentation for users.
In particular:
- added information in the modules reference
- links to the module reference where appropriate
- no full coverage though
- line lengths in code snippets that avoid sliders in the html
representation
- style and typo fixes
> Some documentation polishing and min. code cleanup

- .travis.yml
- doc/source/module_documentation.rst
- neomodel/__init__.py
- neomodel/cardinality.py
- neomodel/contrib/semi_structured.py
- neomodel/core.py
- neomodel/exception.py
- neomodel/exceptions.py
- neomodel/match.py
- neomodel/properties.py
- neomodel/relationship_manager.py
- neomodel/util.py
- test/test_batch.py
- test/test_exceptions.py
- test/test_match_api.py
- test/test_models.py
- test/test_properties.py
nothing fancy, just a cleanup.
> Consolidation of exceptions

- neomodel/relationship_manager.py
The import in question is done at the top of the file, so this import is unecessary
> Remove a weird import with a TODO

- Changelog
- doc/source/conf.py
- doc/source/properties.rst
- doc/source/relationships.rst
- neomodel/__init__.py
- neomodel/core.py
- neomodel/exceptions.py
- neomodel/hooks.py
- neomodel/match.py
- neomodel/properties.py
- test/test_properties.py
unless i oversaw something there was no functionality of bulk setting of  a node's properties which i found to be useful.
> Adds an update method to StructuredNode and other stuff

- doc/source/relationships.rst
- neomodel/match.py
- test/test_match_api.py
i encountered weird behaviour when i had a key's name wrong..
Robin, i haven't forgotten your email, you can guess how much capacities are available to me atm.
> Adds a check for Traversal's definition argument

- doc/source/queries.rst
- neomodel/__init__.py
- neomodel/match.py
- neomodel/match_q.py
- test/test_match_api.py
Implemented Q() filter and exclude like Django.
(Filter with OR #332)
> Added support for Q() in filter and exclude .

- neomodel/core.py
- test/test_models.py
> Raise ValueError when refreshing a non existent inflated node

- neomodel/match.py
- neomodel/match_q.py
- test/test_match_api.py
> Bug filter with or works incorrect

- test/test_match_api.py
``OR`` and ``AND``  filter together tests
> Added test

- doc/source/transactions.rst
- neomodel/relationship.py
- neomodel/util.py
To Overcome the Deprecation Warning in relationship.py and util.py.
To correct a typo in transactions.rst.
> Update relationship.py, util.py and transactions.rst

- neomodel/core.py
- neomodel/exceptions.py
- neomodel/match.py
- neomodel/match_q.py
- neomodel/properties.py
- neomodel/relationship.py
- neomodel/relationship_manager.py
- neomodel/util.py
I found some older string format pattern.
Updated and made a standard for string formatting.
> Standard for string format

- neomodel/match.py
Following #404 I added a "`lazy`" switch to `NodeSet` `get()` and `all()` to allow returning nodes IDs instead of the full node properties.
The code should not break any previous functionality/behavior as the logic stays the same without explicitly specifying the optional argument.
I decided to put the return logic in the `_exeucte` function to keep the code style in `_constains` and `_count` which also change the return (`self._ast['return']`) behavior
> add lazy option to NodeSet get() and all()

- neomodel/contrib/spatial_properties.py
- neomodel/util.py
- setup.py
- test/test_contrib/test_spatial_properties.py
- test/test_transactions.py
Attempting to run Travis tests on the branch
> Upgraded neo4j python driver to 1.7.2

- neomodel/contrib/spatial_properties.py
- test/test_contrib/test_spatial_properties.py
Bug fix in response to issue #417.
> Fixed NeomodelPoint instantiation via copy, deepcopy operations.

- neomodel/properties.py
- test/test_properties.py
Based on initial work contributed by @Lazy-Y.
> Added `max_length` constraint on `StringProperty`

- setup.cfg
- test/test_contrib/test_spatial_datatypes.py
- test/test_contrib/test_spatial_properties.py
- tests-with-docker-compose.sh
Fixes [issue 427](https://github.com/neo4j-contrib/neomodel/issues/427)
> Fix/tests with docker compose.sh

- docker-compose.yml
- setup.py
- tests-with-docker-compose.sh
> Docker compose

- Changelog
- neomodel/util.py
- setup.py
Fixes https://github.com/neo4j-contrib/django-neomodel/issues/62
> don't use encrypted and trust options for secure schemas

- neomodel/util.py
When a database password contains some "special characters", like "?", it causes `set_connection` to raise an exception (URL parsing fails). This pull request url-quotes the password before the parsing, then url-unquotes it.
> Handle db passwords with special chars

- doc/source/relationships.rst
- neomodel/core.py
- neomodel/exceptions.py
- neomodel/relationship_manager.py
- neomodel/util.py
- test/test_issue283.py
This would make it possible to address #130 and #392. 
While the main functionality works, there are still a few things to confirm before merging. (Work in progress).
> Adding object resolution for Relationship type objects 

- README.rst
How's this? 
For support with Aura-specific things, how about sending people to the Aura Discord channel?
> addressing #597

- doc/source/transactions.rst
- neomodel/util.py
- test/conftest.py
- test/test_transactions.py
This pull request adds support for Neo4J bookmarks in both decorated transactions and explicit transactions.
> Add support for bookmarks in transactions

- neomodel/relationship_manager.py
- test/test_issue600.py
> Fix #600 unexpected RelationshipClassRedefined for siblings with same label

- README.rst
- doc/source/relationships.rst
Add relationship index ; Update Neo4j version requirements
> Update doc for 5.0.0 changes

- doc/source/index.rst
Had forgotten to update doc homepage with new versions support
> Update requirements doc homepage

- doc/source/conf.py
- doc/source/index.rst
- requirements.txt
Minor doc issues fixed in these two commits.
**EDIT:** The last commit adds the [sphinx-copybutton](https://sphinx-copybutton.readthedocs.io/en/latest/) to all code samples automatically. This is a very convenient feature for users to quickly copy code from the examples and after [recent experiences](https://github.com/neo4j-contrib/neomodel/issues/692) I see this as a way to encourage users to try things out directly from the docs to catch as many of those 'bugs' as possible.
> Fix doc issues

- .github/workflows/integration-tests.yml
- .gitignore
- neomodel/core.py
- neomodel/exceptions.py
- pyproject.toml
- test/test_cardinality.py
- test/test_indexing.py
- test/test_issue283.py
- test/test_label_install.py
- test/test_match_api.py
Increasing code coverage of tests ; also adding code coverage report generation to default pytest command
> Increase code coverage

- neomodel/contrib/spatial_properties.py
- neomodel/core.py
- neomodel/exceptions.py
- neomodel/match.py
- neomodel/match_q.py
- neomodel/properties.py
- neomodel/relationship_manager.py
- neomodel/util.py
> Turned use of format to f-strings

- .readthedocs.yaml
- doc/requirements.txt
Added (and tested) the rtd configuration file as per [this announcement](https://blog.readthedocs.com/migrate-configuration-v2/)
> Add RTD configuration

- neomodel/contrib/spatial_properties.py
Two criticals remain but they require a bit more attention to correct them properly.
> Corrected the obvious suggestions from sonar in spatial properties

- doc/source/transactions.rst
- neomodel/util.py
- test/conftest.py
- test/test_driver_options.py
> Impersonation

- .github/workflows/integration-tests.yml
- doc/source/transactions.rst
- neomodel/exceptions.py
- neomodel/util.py
- test/conftest.py
- test/test_driver_options.py
- test/test_indexing.py
> Make neomodel Neo4j edition aware

- test/test_connection.py
After each connection to Aura in the test, we reconnect to the initial URL to not impact subsequent tests.
It is cleaner to put this into a teardown fixture ; and it might also fix the random Aura connection test failures.
> Extract connection to prev_url into fixture

- neomodel/core.py
- neomodel/relationship.py
- test/test_models.py
Make sure to return ValueError with explanation for reserved keywords :
* Nodes :
* deleted
* id
* element_id
* Rels :
* source
* target
Includes test coverage
> Improve reserved keyword error ; add tests

- .github/workflows/integration-tests.yml
- doc/source/cypher.rst
- doc/source/getting_started.rst
- neomodel/integration/numpy.py
- neomodel/integration/pandas.py
- pyproject.toml
- test/test_cypher.py
Adds support for casting cypher_query results to :
- pandas DataFrame and Series
- numpy Array
> Add pandas and numpy format support

- neomodel/scripts/neomodel_install_labels.py
- neomodel/scripts/neomodel_remove_labels.py
- test/async_/test_models.py
- test/conftest.py
- test/sync_/test_models.py
> Remove python2 print leftover

- doc/source/getting_started.rst
- neomodel/exceptions.py
- test/async_/test_match_api.py
- test/sync_/test_match_api.py
Improve the content of the exception, and improve&fix the documentation on the `fetch_relations` part. Add test for the exception
> Improve exception content; fix documentation

- doc/source/getting_started.rst
- doc/source/index.rst
- doc/source/schema_management.rst
- neomodel/async_/core.py
- neomodel/properties.py
- neomodel/sync_/core.py
- test/async_/test_label_install.py
- test/sync_/test_label_install.py
> Add support for full-text index creation #810

- doc/source/schema_management.rst
- neomodel/__init__.py
- neomodel/async_/core.py
- neomodel/properties.py
- neomodel/sync_/core.py
- test/async_/test_label_install.py
- test/sync_/test_label_install.py
- Add support for vector indexes
- Improves and unifies vector and fulltext syntax
- Extend code coverage for exceptions
- Fixes a few code smells
- Includes documentation
> Support for Vector indexes #756

- neomodel/async_/match.py
- neomodel/sync_/match.py
- test/async_/test_match_api.py
- test/sync_/test_match_api.py
Filters related to variables coming from MATCH statements will now be injected into a dedicated WHERE statement coming just after MATCH statements.
> Split filters coming from MATCH and OPTIONAL MATCH statements.

- Changelog
- doc/source/advanced_query_operations.rst
- doc/source/getting_started.rst
- doc/source/traversal.rst
- neomodel/async_/match.py
- neomodel/sync_/match.py
- test/async_/test_match_api.py
- test/sync_/test_match_api.py
It will replace both fetch_relations() and traverse_relations()
> Introduced new traverse() method.
